version: '3.8'

services:

  pma:
    depends_on:
      - maria

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        - traefik.http.services.laravel_pma.loadbalancer.server.port=80

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

        # Router: HTTP
        - traefik.http.routers.laravel_pma_http.rule=Host(`pma.${HOST}`)
        - traefik.http.routers.laravel_pma_http.entrypoints=http
        - traefik.http.routers.laravel_pma_http.middlewares=https-redirect

        # Router: HTTPS
        - traefik.http.routers.laravel_pma_https.rule=Host(`pma.${HOST}`)
        - traefik.http.routers.laravel_pma_https.entrypoints=https
        - traefik.http.routers.laravel_pma_https.tls=true
        - traefik.http.routers.laravel_pma_https.tls.certresolver=le

    image: phpmyadmin:latest

    networks:
      - maria
      - traefik

networks:
  maria:
  traefik:
    external: true
