version: '3.8'

services:

  queue:
    depends_on:
      - app

    image: *BASE_IMAGE*/queue:${QUEUE_VERSION}

    networks:
      - maria

    volumes:
      - public_storage:/var/www/html/storage/app/public
      - storage:/var/www/html/storage/app

      - queue_framework_cache_data:/var/www/html/storage/framework/cache/data
      - queue_logs:/var/www/html/storage/logs

    secrets:
      - source: laravel_env
        target: /var/www/html/.env

networks:
  maria:

volumes:
  queue_framework_cache_data:
  queue_logs:

secrets:
  laravel_env:
    external: true
