version: '3.8'

services:

  schedule:
    depends_on:
      - app

    image: *BASE_IMAGE*/schedule:${SCHEDULE_VERSION}

    networks:
      - maria

    volumes:
      - public_storage:/var/www/html/storage/app/public
      - storage:/var/www/html/storage/app

      - schedule_framework_cache_data:/var/www/html/storage/framework/cache/data
      - schedule_logs:/var/www/html/storage/logs

    secrets:
      - source: laravel_env
        target: /var/www/html/.env

networks:
  maria:

volumes:
  schedule_framework_cache_data:
  schedule_logs:

secrets:
  laravel_env:
    external: true
