version: '3.8'

services:

  webserver:
    depends_on:
      - app

    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.constraint-label=traefik
        - traefik.http.services.laravel_webserver.loadbalancer.server.port=80

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # - traefik.http.middlewares.laravel_webserver_auth.basicauth.users=root:${WEBSERVER_HASHED_PASSWORD}

        # Router: HTTP
        - traefik.http.routers.laravel_webserver_http.rule=Host(`${HOST}`)
        - traefik.http.routers.laravel_webserver_http.entrypoints=http
        - traefik.http.routers.laravel_webserver_http.middlewares=https-redirect

        # Router: HTTPS
        - traefik.http.routers.laravel_webserver_https.rule=Host(`${HOST}`)
        - traefik.http.routers.laravel_webserver_https.entrypoints=https
        - traefik.http.routers.laravel_webserver_https.tls=true
        - traefik.http.routers.laravel_webserver_https.tls.certresolver=le
        # - traefik.http.routers.laravel_webserver_https.middlewares=laravel_webserver_auth

    image: *BASE_IMAGE*/webserver:${WEBSERVER_VERSION}

    networks:
      - app
      - traefik

networks:
  app:
  traefik:
    external: true
